### ISSUE TITLE
Model with further compression

### ISSUE THREAD

**Issue by ZiruiYan** [MiaoyunZhao/GANmemory_LifelongLearning#1]
Hi, 
Thanks for this excellent paper. Could you upload the model with further compression?  I think compression is one of the highlights of the article.

**Comment by MiaoyunZhao** [comment]
> Hi,
> Thanks for this excellent paper. Could you upload the model with further compression? I think compression is one of the highlights of the article.

Thanks for your suggestions. The compression part is uploaded.

**Comment by ZiruiYan** [comment]
Thanks for that!
