### ISSUE TITLE
the pretrained model

### ISSUE THREAD

**Issue by leatherking** [MiaoyunZhao/GANmemory_LifelongLearning#2]
Thanks for your codes uploaded. The urls of pretrained models are unavailable maybe the amazonaws server is on due. Is there any other way to download the pretrained models? Best regards.

**Comment by MiaoyunZhao** [comment]
> Thanks for your codes uploaded. The urls of pretrained models are unavailable maybe the amazonaws server is on due. Is there any other way to download the pretrained models? Best regards.

With the following two links, you can download the model and go to the second step directly. 
https://drive.google.com/file/d/18dsfLHhZtUPqoHFdAUm9ZqmUIcuPH423/view?usp=sharing
https://drive.google.com/file/d/1dbIbV61RqKqOiLdTNRsmFzeESAKO0NKp/view?usp=sharing

**Comment by leatherking** [comment]
> > Thanks for your codes uploaded. The urls of pretrained models are unavailable maybe the amazonaws server is on due. Is there any other way to download the pretrained models? Best regards.
> 
> With the following two links, you can download the model and go to the second step directly.
> https://drive.google.com/file/d/18dsfLHhZtUPqoHFdAUm9ZqmUIcuPH423/view?usp=sharing
> https://drive.google.com/file/d/1dbIbV61RqKqOiLdTNRsmFzeESAKO0NKp/view?usp=sharing

Many thanks for your help.
